[package]
name = "counter"
version = "0.0.1"

[addresses]
counter = "_"

[dependencies]
layerzero = { local = "../../../../../../packages/layerzero-v1/aptos/contracts/layerzero" }
layerzero_common = { local = "../../../../../../packages/layerzero-v1/aptos/contracts/layerzero-common" }
layerzero_view = { local = "../../../../../../packages/layerzero-v1/aptos/contracts/layerzero-view" }