[package]
name = "counter"
version = "0.0.1"

[addresses]
counter = "_"

[dependencies]
layerzero = { local = "../../layerzero" }
layerzero_common = { local = "../../layerzero-common" }
layerzero_view = { local = "../../layerzero-view" }