include Makefile.config
export PATH := deps/aptos-core/target/release/:$(PATH)

.PHONY: build install-aptos test compile local-node

install-aptos:
	cd deps/aptos-core && cargo install --profile release --path crates/aptos

clean:
	rm -rf layerzero/build && rm -rf apps/bridge/build && rm -rf apps/oracle/build

build:
	cd deps/aptos-core && cargo build --profile release

test-common:
	cd layerzero-common && aptos move test --named-addresses layerzero_common=${layerzero_common}

test-layerzero:
	cd layerzero && aptos move test --named-addresses layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v1_1=${msglib_v1_1},msglib_v2=${msglib_v2},layerzero=${layerzero},executor_auth=${executor_auth},executor_v2=${executor_v2},test=${test},lzapp=${lzapp},msglib_v2_1=${msglib_v2_1},msglib_v3=${msglib_v3},uln_301=${uln_301},msglib_routing_helper=${msglib_routing_helper},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},fa_converter=${fa_converter},packet_converter=${packet_converter},executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury}

test-oracle:
	cd apps/oracle && aptos move test --named-addresses layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v1_1=${msglib_v1_1},msglib_v2=${msglib_v2},executor_auth=${executor_auth},executor_v2=${executor_v2},layerzero=${layerzero},oracle=${oracle},msglib_v2_1=${msglib_v2_1},msglib_v3=${msglib_v3},uln_301=${uln_301},msglib_routing_helper=${msglib_routing_helper},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},fa_converter=${fa_converter},packet_converter=${packet_converter},executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury}

test-counter:
	cd apps/counter && aptos move test --named-addresses layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v1_1=${msglib_v1_1},msglib_v2=${msglib_v2},executor_auth=${executor_auth},executor_v2=${executor_v2},layerzero=${layerzero},counter=${counter},layerzero_view=${layerzero_view},msglib_v2_1=${msglib_v2_1},msglib_v3=${msglib_v3},uln_301=${uln_301},msglib_routing_helper=${msglib_routing_helper},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},fa_converter=${fa_converter},packet_converter=${packet_converter},executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury}

test-bridge:
	cd apps/bridge && aptos move test --named-addresses layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v1_1=${msglib_v1_1},msglib_v2=${msglib_v2},executor_auth=${executor_auth},executor_v2=${executor_v2},layerzero=${layerzero},bridge=${bridge},msglib_v2_1=${msglib_v2_1},msglib_v3=${msglib_v3},uln_301=${uln_301},msglib_routing_helper=${msglib_routing_helper},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},fa_converter=${fa_converter},packet_converter=${packet_converter},executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury}

test-layerzero-apps:
	cd layerzero-apps && aptos move test --named-addresses layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v1_1=${msglib_v1_1},msglib_v2=${msglib_v2},executor_auth=${executor_auth},executor_v2=${executor_v2},layerzero=${layerzero},layerzero_apps=${layerzero_apps},msglib_v2_1=${msglib_v2_1},msglib_v3=${msglib_v3},uln_301=${uln_301},msglib_routing_helper=${msglib_routing_helper},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},fa_converter=${fa_converter},packet_converter=${packet_converter},executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury}

test-oft:
	cd apps/example/oft && aptos move test --named-addresses layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v1_1=${msglib_v1_1},msglib_v2=${msglib_v2},executor_auth=${executor_auth},executor_v2=${executor_v2},layerzero=${layerzero},layerzero_apps=${layerzero_apps},oft=${oft},msglib_v2_1=${msglib_v2_1},msglib_v3=${msglib_v3},uln_301=${uln_301},msglib_routing_helper=${msglib_routing_helper},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},fa_converter=${fa_converter},packet_converter=${packet_converter},executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury}

test-proxy-oft:
	cd apps/example/proxy-oft && aptos move test --named-addresses layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v1_1=${msglib_v1_1},msglib_v2=${msglib_v2},executor_auth=${executor_auth},executor_v2=${executor_v2},layerzero=${layerzero},layerzero_apps=${layerzero_apps},proxy_oft=${proxy_oft},msglib_v2_1=${msglib_v2_1},msglib_v3=${msglib_v3},uln_301=${uln_301},msglib_routing_helper=${msglib_routing_helper},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},fa_converter=${fa_converter},packet_converter=${packet_converter},executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury}

test-executor-ext:
	cd executor/executor-ext && aptos move test --named-addresses executor_ext=${executor_ext}

test-msglib-auth:
	cd msglib/msglib-auth && aptos move test --named-addresses layerzero_common=${layerzero_common},msglib_auth=${msglib_auth}

test-msglib-v3:
	cd msglib/msglib-v3 && aptos move test --named-addresses layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v3=${msglib_v3}

test-msglib-v2-1:
	cd msglib/msglib-v2/msglib-v2-1 && aptos move test --named-addresses layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v2_1=${msglib_v2_1}

test-packet-converter:
	cd msglib/msglib-utils/packet-converter && aptos move test --named-addresses layerzero_common=${layerzero_common},packet_converter=${packet_converter},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin}

test-fa-converter:
	cd msglib/msglib-utils/fa-converter && aptos move test --named-addresses fa_converter=${fa_converter},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin}

test-executor-fee-lib-v1:
	cd msglib/executor-fee-libs/fee-lib-v1 && aptos move test --named-addresses executor_fee_lib_v1=${executor_fee_lib_v1},uln_301=${uln_301},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},executor_fee_lib_0=${executor_fee_lib_0}

test-executor-fee-lib-router-v3:
	cd msglib/executor-fee-lib-routers/router-v3 && aptos move test --named-addresses executor_fee_lib_router_v3=${executor_fee_lib_router_v3}

test-executor-fee-lib-router-v2:
	cd msglib/executor-fee-lib-routers/router-v2 && aptos move test --named-addresses executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},uln_301=${uln_301},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},executor_fee_lib_0=${executor_fee_lib_0}

test-executor-fee-lib-router-v1:
	cd msglib/executor-fee-lib-routers/router-v1 && aptos move test --named-addresses executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},uln_301=${uln_301},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},executor_fee_lib_0=${executor_fee_lib_0}

test-executor-v2-fee-lib-router-v2:
	cd executor/fee-lib-routers/router-v2 && aptos move test --named-addresses executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2}

test-executor-v2-fee-lib-router-v1:
	cd executor/fee-lib-routers/router-v1 && aptos move test --named-addresses executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},executor_v2=${executor_v2},layerzero_common=${layerzero_common},executor_auth=${executor_auth},executor_fee_lib_v1=${executor_fee_lib_v1},uln_301=${uln_301},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},executor_fee_lib_0=${executor_fee_lib_0}

test-executor-auth:
	cd executor/executor-auth && aptos move test --named-addresses layerzero_common=${layerzero_common},executor_auth=${executor_auth}

test-executor-v2:
	cd executor/executor-v2 && aptos move test --named-addresses layerzero_common=${layerzero_common},executor_auth=${executor_auth},executor_v2=${executor_v2},executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},uln_301=${uln_301},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},executor_fee_lib_0=${executor_fee_lib_0}

test-uln-301:
	cd msglib/msglib-v2/msglib-v2-0/uln-301 && aptos move test --named-addresses uln_301=${uln_301},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},layerzero_common=${layerzero_common},zro=${zro},msglib_auth=${msglib_auth},fa_converter=${fa_converter},packet_converter=${packet_converter},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury}

test-uln-301-receive-helper:
	cd msglib/msglib-v2/msglib-v2-0/uln-301-receive-helper && aptos move test --named-addresses uln_301_receive_helper=${uln_301_receive_helper},uln_301=${uln_301},layerzero=${layerzero},layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v1_1=${msglib_v1_1},msglib_v2=${msglib_v2},executor_auth=${executor_auth},executor_v2=${executor_v2},packet_converter=${packet_converter},fa_converter=${fa_converter},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury},msglib_routing_helper=${msglib_routing_helper},msglib_v2_1=${msglib_v2_1},msglib_v3=${msglib_v3}

test-msglib-routing-helper:
	cd msglib/msglib-v2/msglib-v2-0/msglib-routing-helper && aptos move test --named-addresses msglib_routing_helper=${msglib_routing_helper},layerzero=${layerzero},layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v1_1=${msglib_v1_1},msglib_v2=${msglib_v2},executor_auth=${executor_auth},executor_v2=${executor_v2},msglib_v2_1=${msglib_v2_1},msglib_v3=${msglib_v3},uln_301=${uln_301},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},fa_converter=${fa_converter},packet_converter=${packet_converter},executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury}

test-msglib-v2-router:
	cd msglib/msglib-v2/msglib-v2-0/msglib-v2-router && aptos move test --named-addresses msglib_v2=${msglib_v2},layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v2_1=${msglib_v2_1},msglib_v3=${msglib_v3},uln_301=${uln_301},msglib_routing_helper=${msglib_routing_helper},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},fa_converter=${fa_converter},packet_converter=${packet_converter},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury}

test-zro:
	cd zro && aptos move test --named-addresses zro=${zro}

test-layerzero-view:
	cd layerzero-view && aptos move test --named-addresses layerzero_view=${layerzero_view},layerzero=${layerzero},layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v1_1=${msglib_v1_1},msglib_v2=${msglib_v2},executor_auth=${executor_auth},executor_v2=${executor_v2},msglib_v2_1=${msglib_v2_1},msglib_v3=${msglib_v3},uln_301=${uln_301},msglib_routing_helper=${msglib_routing_helper},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},fa_converter=${fa_converter},packet_converter=${packet_converter},executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury},test=${test},lzapp=${lzapp}

test: test-common test-layerzero test-oracle test-counter test-bridge test-layerzero-apps test-oft test-proxy-oft test-executor-ext test-msglib-auth test-msglib-v3 test-msglib-v2-1 test-packet-converter test-fa-converter test-executor-fee-lib-v1 test-executor-fee-lib-router-v3 test-executor-fee-lib-router-v2 test-executor-fee-lib-router-v1 test-executor-v2-fee-lib-router-v2 test-executor-v2-fee-lib-router-v1 test-executor-auth test-executor-v2 test-uln-301 test-uln-301-receive-helper test-msglib-routing-helper test-msglib-v2-router test-zro test-layerzero-view

compile-common:
	cd layerzero-common && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses layerzero_common=${layerzero_common}

compile-zro:
	cd zro && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses zro=${zro}

compile-msglib-auth:
	cd ./msglib/msglib-auth && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses layerzero_common=${layerzero_common},msglib_auth=${msglib_auth}

compile-msglib-v1-1:
	cd ./msglib/msglib-v1/msglib-v1-1 && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v1_1=${msglib_v1_1}

compile-layerzero:
	cd layerzero && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v1_1=${msglib_v1_1},msglib_v2=${msglib_v2},layerzero=${layerzero},executor_auth=${executor_auth},executor_v2=${executor_v2},test=${test},lzapp=${lzapp},msglib_v2_1=${msglib_v2_1},msglib_v3=${msglib_v3},uln_301=${uln_301},msglib_routing_helper=${msglib_routing_helper},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},fa_converter=${fa_converter},packet_converter=${packet_converter},executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury}

compile-executor-auth:
	cd ./executor/executor-auth && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses layerzero_common=${layerzero_common},executor_auth=${executor_auth}

compile-executor-v2:
	cd ./executor/executor-v2 && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses layerzero_common=${layerzero_common},executor_auth=${executor_auth},executor_v2=${executor_v2},executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},uln_301=${uln_301},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},executor_fee_lib_0=${executor_fee_lib_0}

compile-executor-ext:
	cd ./executor/executor-ext && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses executor_ext=${executor_ext}

compile-oracle:
	cd apps/oracle && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v1_1=${msglib_v1_1},msglib_v2=${msglib_v2},executor_auth=${executor_auth},executor_v2=${executor_v2},layerzero=${layerzero},oracle=${oracle},msglib_v2_1=${msglib_v2_1},msglib_v3=${msglib_v3},uln_301=${uln_301},msglib_routing_helper=${msglib_routing_helper},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},fa_converter=${fa_converter},packet_converter=${packet_converter},executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury}

compile-counter:
	cd apps/counter && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v1_1=${msglib_v1_1},msglib_v2=${msglib_v2},executor_auth=${executor_auth},executor_v2=${executor_v2},layerzero=${layerzero},counter=${counter},layerzero_view=${layerzero_view},msglib_v2_1=${msglib_v2_1},msglib_v3=${msglib_v3},uln_301=${uln_301},msglib_routing_helper=${msglib_routing_helper},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},fa_converter=${fa_converter},packet_converter=${packet_converter},executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury}

compile-bridge:
	cd apps/bridge && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v1_1=${msglib_v1_1},msglib_v2=${msglib_v2},executor_auth=${executor_auth},executor_v2=${executor_v2},layerzero=${layerzero},bridge=${bridge},msglib_v2_1=${msglib_v2_1},msglib_v3=${msglib_v3},uln_301=${uln_301},msglib_routing_helper=${msglib_routing_helper},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},fa_converter=${fa_converter},packet_converter=${packet_converter},executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury}

compile-msglib-v3:
	cd msglib/msglib-v3 && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v3=${msglib_v3}

compile-msglib-v2-1:
	cd msglib/msglib-v2/msglib-v2-1 && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v2_1=${msglib_v2_1}

compile-packet-converter:
	cd msglib/msglib-utils/packet-converter && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses layerzero_common=${layerzero_common},packet_converter=${packet_converter},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin}

compile-fa-converter:
	cd msglib/msglib-utils/fa-converter && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses fa_converter=${fa_converter},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin}

compile-executor-fee-lib-v1:
	cd msglib/executor-fee-libs/fee-lib-v1 && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses executor_fee_lib_v1=${executor_fee_lib_v1},uln_301=${uln_301},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},executor_fee_lib_0=${executor_fee_lib_0}

compile-executor-fee-lib-router-v3:
	cd msglib/executor-fee-lib-routers/router-v3 && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses executor_fee_lib_router_v3=${executor_fee_lib_router_v3}

compile-executor-fee-lib-router-v2:
	cd msglib/executor-fee-lib-routers/router-v2 && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},uln_301=${uln_301},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},executor_fee_lib_0=${executor_fee_lib_0}

compile-executor-fee-lib-router-v1:
	cd msglib/executor-fee-lib-routers/router-v1 && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},uln_301=${uln_301},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},executor_fee_lib_0=${executor_fee_lib_0}

compile-executor-v2-fee-lib-router-v2:
	cd executor/fee-lib-routers/router-v2 && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2}

compile-executor-v2-fee-lib-router-v1:
	cd executor/fee-lib-routers/router-v1 && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},executor_v2=${executor_v2},layerzero_common=${layerzero_common},executor_auth=${executor_auth},executor_fee_lib_v1=${executor_fee_lib_v1},uln_301=${uln_301},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},executor_fee_lib_0=${executor_fee_lib_0}

compile-uln-301:
	cd msglib/msglib-v2/msglib-v2-0/uln-301 && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses uln_301=${uln_301},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},layerzero_common=${layerzero_common},zro=${zro},msglib_auth=${msglib_auth},fa_converter=${fa_converter},packet_converter=${packet_converter},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury}

compile-uln-301-receive-helper:
	cd msglib/msglib-v2/msglib-v2-0/uln-301-receive-helper && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses uln_301_receive_helper=${uln_301_receive_helper},uln_301=${uln_301},layerzero=${layerzero},layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v1_1=${msglib_v1_1},msglib_v2=${msglib_v2},executor_auth=${executor_auth},executor_v2=${executor_v2},packet_converter=${packet_converter},fa_converter=${fa_converter},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury},msglib_routing_helper=${msglib_routing_helper},msglib_v2_1=${msglib_v2_1},msglib_v3=${msglib_v3}

compile-msglib-routing-helper:
	cd msglib/msglib-v2/msglib-v2-0/msglib-routing-helper && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses msglib_routing_helper=${msglib_routing_helper},layerzero=${layerzero},layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v1_1=${msglib_v1_1},msglib_v2=${msglib_v2},executor_auth=${executor_auth},executor_v2=${executor_v2},msglib_v2_1=${msglib_v2_1},msglib_v3=${msglib_v3},uln_301=${uln_301},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},fa_converter=${fa_converter},packet_converter=${packet_converter},executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury}

compile-msglib-v2-router:
	cd msglib/msglib-v2/msglib-v2-0/msglib-v2-router && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses msglib_v2=${msglib_v2},layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v2_1=${msglib_v2_1},msglib_v3=${msglib_v3},uln_301=${uln_301},msglib_routing_helper=${msglib_routing_helper},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},fa_converter=${fa_converter},packet_converter=${packet_converter},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury}

compile-layerzero-apps:
	cd layerzero-apps && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v1_1=${msglib_v1_1},msglib_v2=${msglib_v2},executor_auth=${executor_auth},executor_v2=${executor_v2},layerzero=${layerzero},layerzero_apps=${layerzero_apps},msglib_v2_1=${msglib_v2_1},msglib_v3=${msglib_v3},uln_301=${uln_301},msglib_routing_helper=${msglib_routing_helper},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},fa_converter=${fa_converter},packet_converter=${packet_converter},executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury}

compile-layerzero-view:
	cd layerzero-view && aptos move compile --included-artifacts=${included_artifacts} --save-metadata --named-addresses layerzero_view=${layerzero_view},layerzero=${layerzero},layerzero_common=${layerzero_common},msglib_auth=${msglib_auth},zro=${zro},msglib_v1_1=${msglib_v1_1},msglib_v2=${msglib_v2},executor_auth=${executor_auth},executor_v2=${executor_v2},msglib_v2_1=${msglib_v2_1},msglib_v3=${msglib_v3},uln_301=${uln_301},msglib_routing_helper=${msglib_routing_helper},executor_fee_lib_router_v1=${executor_fee_lib_router_v1},executor_fee_lib_router_v2=${executor_fee_lib_router_v2},executor_fee_lib_v1=${executor_fee_lib_v1},executor_fee_lib_router_v3=${executor_fee_lib_router_v3},fa_converter=${fa_converter},packet_converter=${packet_converter},executor_v2_fee_lib_router_v1=${executor_v2_fee_lib_router_v1},executor_v2_fee_lib_router_v2=${executor_v2_fee_lib_router_v2},dvn_fee_lib_0=${dvn_fee_lib_0},endpoint_v2=${endpoint_v2},endpoint_v2_common=${endpoint_v2_common},layerzero_admin=${layerzero_admin},layerzero_treasury_admin=${layerzero_treasury_admin},msglib_types=${msglib_types},price_feed_module_0=${price_feed_module_0},price_feed_router_0=${price_feed_router_0},price_feed_router_1=${price_feed_router_1},worker_common=${worker_common},dvn_fee_lib_router_0=${dvn_fee_lib_router_0},dvn_fee_lib_router_1=${dvn_fee_lib_router_1},executor_fee_lib_0=${executor_fee_lib_0},treasury=${treasury},test=${test},lzapp=${lzapp}

compile: compile-common compile-msglib-auth compile-zro compile-msglib-v1-1 compile-msglib-v3 compile-msglib-v2-1 compile-packet-converter compile-fa-converter compile-executor-fee-lib-v1 compile-executor-fee-lib-router-v3 compile-executor-fee-lib-router-v2 compile-executor-fee-lib-router-v1 compile-executor-v2-fee-lib-router-v2 compile-executor-v2-fee-lib-router-v1 compile-uln-301 compile-uln-301-receive-helper compile-msglib-routing-helper compile-msglib-v2-router compile-layerzero compile-counter compile-bridge compile-oracle compile-executor-v2 compile-executor-auth compile-executor-ext compile-layerzero-apps compile-layerzero-view

local-node:
	@-pkill -f aptos
	rm -rf .aptos
	aptos node run-local-testnet --with-faucet &
	@curl --silent --retry 15 --retry-delay 2 --retry-connrefused http://localhost:8080/
	@curl --silent --retry 15 --retry-delay 2 --retry-connrefused http://localhost:8081/
