[package]
name = "uln_301_receive_helper"
version = "1.0.0"
authors = []

[addresses]
uln_301_receive_helper = "_"

uln_301 = "_"
layerzero_common = "_"
msglib_auth = "_"
endpoint_v2_common = "_"
packet_converter = "_"

[dependencies]
uln_301 = { local = "../uln-301" }
layerzero = { local = "../../../../interfaces-mock/layerzero" }
layerzero_common = { local = "../../../../interfaces-mock/layerzero-common" }
msglib_auth = { local = "../../../../interfaces-mock/msglib-auth" }
endpoint_v2_common = { git = "https://github.com/LayerZero-Labs/LayerZero-v2", rev = "main", subdir = "packages/layerzero-v2/aptos/contracts/endpoint_v2_common" }
packet_converter = { local = "../../../msglib-utils/packet-converter" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "2c995bf668b2233825dde26137c3d1b076e99c22" }

[dev-dependencies] 