[package]
name = "layerzero"
version = "0.0.1"

[addresses]
layerzero = "_"

[dev-addresses]
layerzero = '0x1003'

[dependencies]
# This can be used to build EndpointV2-related contracts only
msglib_auth = { local = "../msglib-auth" }
layerzero_common = { local = "../layerzero-common" }