[package]
name = "msglib_v3"
version = "0.0.1"

[addresses]
msglib_v3 = "_"
layerzero_common = "_"
msglib_auth = "_"
zro = "_"

[dependencies]
layerzero_common = { local = "../../layerzero-common" }
msglib_auth = { local = "../msglib-auth" }
zro = { local = "../../zro" }
