[package]
name = "executor_v2"
version = "0.0.1"

[addresses]
executor_v2 = "_"

layerzero_common = "_"
executor_auth = "_"

[dependencies]
layerzero_common = { local = "../../layerzero-common" }
executor_auth = { local = "../executor-auth" }
endpoint_v2_common = { git = "https://github.com/LayerZero-Labs/LayerZero-v2", rev = "main", subdir = "packages/layerzero-v2/aptos/contracts/endpoint_v2_common" }
executor_v2_fee_lib_router_v1 = { local = "../fee-lib-routers/router-v1" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "2c995bf668b2233825dde26137c3d1b076e99c22" }
