[package]
name = "zro"
version = "0.0.1"

[addresses]
zro = "_"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/move-stdlib"
rev = "2a332586aa4ec6b6eb5372b43e6b13d40061c6a5"