[package]
name = "executor_fee_lib_v1"
version = "1.0.0"

[addresses]
executor_fee_lib_v1 = "_"
uln_301 = "_"

[dev-addresses]


[dependencies]
executor_fee_lib_0 = { git = "https://github.com/LayerZero-Labs/LayerZero-v2", rev = "main", subdir = "packages/layerzero-v2/aptos/contracts/worker_peripherals/fee_libs/executor_fee_lib_0" }
worker_common = { git = "https://github.com/LayerZero-Labs/LayerZero-v2", rev = "main", subdir = "packages/layerzero-v2/aptos/contracts/worker_peripherals/worker_common" }
price_feed_router_0 = { git = "https://github.com/LayerZero-Labs/LayerZero-v2", rev = "main", subdir = "packages/layerzero-v2/aptos/contracts/worker_peripherals/price_feed_routers/price_feed_router_0" }
msglib_types = { git = "https://github.com/LayerZero-Labs/LayerZero-v2", rev = "main", subdir = "packages/layerzero-v2/aptos/contracts/msglib/msglib_types" }
endpoint_v2_common = { git = "https://github.com/LayerZero-Labs/LayerZero-v2", rev = "main", subdir = "packages/layerzero-v2/aptos/contracts/endpoint_v2_common" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "2c995bf668b2233825dde26137c3d1b076e99c22" }